config/routes.rb
Sdszombi::Application.routes.draw do
	resources :zombies

	root to: 'zombies#index'

	match "/auth/:provider/callback" => "zombies#twitter_callback"
	match '/auth/failure', :to => 'zombies#failure'

	match '/preveri', :to => 'zombies#check_block_status', :as => 'check_block_status'
	match '/nisi-zombi', :to => 'zombies#not_blocked', :as => 'not_blocked'
	match '/si-zombi/:id', :to => 'zombies#show', :as => 'blocked'

	match '/o-strani', to: 'about#index', as: 'about'

end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  attr_accessible :message, :name, :secret, :show
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	before_filter( :provide_zombie_count )

	def provide_zombie_count
		@all_zombies_num = Zombie.count()
	end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
	def index
		@zombies = Zombie.all( order: 'id DESC')
	end

	def not_blocked
	end

	def twitter_callback
		session[:twitter_name] = request.env['omniauth.auth']['info']['nickname']
		session[:twitter_token] = request.env['omniauth.auth']['credentials']['token']
		session[:twitter_secret] = request.env['omniauth.auth']['credentials']['secret']

		redirect_to( check_block_status_path )
	end

	def failure
	end

	def check_block_status
		unless session[:twitter_token] && session[:twitter_secret]
			redirect_to( root_path ) 
			return
		end

		twitter_client = Twitter::Client.new(
			:oauth_token => session[:twitter_token],
			:oauth_token_secret => session[:twitter_secret]
		)

		# check if user is following @strankaSDS
		begin
			twitter_client.friendships( 'strankaSDS' )[0].connections.each do |status|
				if status === 'following'
					# user is not blocked
					redirect_to( not_blocked_path )
					return
				end
			end
		rescue
			redirect_to( not_blocked_path )
			return
		end

		# try to follow @strankaSDS
		follow_check = twitter_client.follow( 'strankaSDS' )

		if follow_check.length > 0
			# follow was successful, user is not blocked
			twitter_client.unfollow( 'strankaSDS' )
			redirect_to( not_blocked_path )
			return
		else
			# user is blocked
			zombie = Zombie.find_by_name( session[:twitter_name] )
			if !zombie
				zombie = Zombie.create( :name => session[:twitter_name], :message => '', :show => true )
				redirect_to blocked_path( zombie )
				return
			else
				redirect_to blocked_path( zombie )
				return
			end
		end
	end

	def show
		begin
			@zombie = Zombie.find( params[:id] )
		rescue
			redirect_to( root_path )
			return
		end

		@show_form = ( session[:twitter_name] && session[:twitter_name] == @zombie.name )
	end

	def update
		@zombie = Zombie.find( params[:id] )

		new_message = params[:zombie][:message]
		if new_message.length > 140
			new_message = new_message[0..139]
		end

		if @zombie.update_attributes( message: new_message )
			redirect_to( blocked_path( @zombie ) )
			return
		else
			redirect_to( root_path )
			return
		end
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_page_title( title )
		if title.blank? then
			'SDS Zombi'
		else
			title + ' - SDS Zombi'
		end
	end
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/about/index.html.erb
<% provide( :title, 'O strani' ) %>
<div id="about">
	<h1>O SDS zombi</h1>
	<p>
		Ta stran je nastala kot odgovor na neprofesionalno komunikacijo stranke SDS na njihovem twitter računu <a href="https://twitter.com/strankasds">@strankaSDS</a>, ter zaradi njihovega pristopa pri obravnavanju demonstracij, ki se dogajajo v Sloveniji.
	</p>
	<p>
		Namen je opozoriti na nedemokratičnost ravnanja stranke SDS, ki blokira drugače misleče državljane ter s tem onemogoča dialog.
	</p>
	<p>
		Mnenja (razlogi za blokiranje) izražena na tej strani so last avtorjev teh mnenj in ne predstavljajo mnenja avtorjev te strani. Avtorji te spletne strani za ta mnenja ne odgovarjajo.
	</p>
	<p>
		Izvorna koda te spletne strani je prosto dostopna na <a href="https://github.com/janhancic/sdszombi.com">tej povezavi</a>. Vsak lahko prispeva k razvoju te spletne strani, vendar je končna odločitev o inkorporaciji sprememb v rokah prvotnih avtorjev.
	</p>
</div>

app/views/layouts/_share.html.erb
<% share_url ||= 'http://www.sdszombi.com' %>
<div id="share">
	<iframe allowtransparency="true" frameborder="0" scrolling="no" src="https://platform.twitter.com/widgets/tweet_button.html?url=<%=u share_url %>&amp;via=SDSzombi" style="width:81px; height:20px;"></iframe>
	<a href="https://twitter.com/SDSzombi" class="twitter-follow-button" data-show-count="true" data-lang="en" data-width="198px">Follow @SDSzombi</a>
	<iframe src="https://www.facebook.com/plugins/like.php?href=<%=u share_url %>&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=like&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:80px; height:21px;" allowTransparency="true"></iframe>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_page_title( yield :title ) %></title>
		<meta name="description" content="Preveri če SDS misli da si zombi. Uporabi twitter račun in poglej če te je @strankaSDS blokirala." />
		<meta property="og:site_name" content="SDSzombi.com" />
		<meta property="og:image" content="<%= image_path('zombi-blank.png') %>" />
		<link rel="shortcut icon" href="/favicon.ico" />
		<%= stylesheet_link_tag( 'application', :media => 'all' ) %>
		<%= csrf_meta_tags %>
		<link href='http://fonts.googleapis.com/css?family=Creepster' rel='stylesheet' type='text/css'>
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1,user-scalable=no" />
	</head>
	<body>
		<div class="row-fluid" id="row-1">
			<a href="/" class="span12">SDS JE BLOKIRALA</a>
		</div>
		<div class="row-fluid" id="row-2">
			<a href="/" class="span12"><%= @all_zombies_num %></a>
		</div>
		<div class="row-fluid" id="row-3">
			<a href="/" class="span12">
				<% if @all_zombies_num === 1 || @all_zombies_num === 2 %>
				ZOMBIJA
				<% elsif @all_zombies_num === 3 || @all_zombies_num === 4 %>
				ZOMBIJE
				<% elsif @all_zombies_num >= 5 %>
				ZOMBIJEV
				<% end %>
			</a>
		</div>
		<%= yield %>

		<footer>
			<a href="<%= about_path %>">o strani</a> | <a href="https://twitter.com/SDSzombi">@SDSzombi</a>
		</footer>

		<%= javascript_include_tag( 'application' ) %>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
		<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', '<%= ENV['SDSZOMBI_ANALYTICS_ID'] %>']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
		</script>
	</body>
</html>

app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :show %><br />
    <%= f.check_box :show %>
  </div>
  <div class="field">
    <%= f.label :secret %><br />
    <%= f.text_field :secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/failure.html.erb
<p style="text-align: center;">
	Ups ... nekaj je šlo narobe. Prosim <a href="https://twitter.com/sdszombi">sporoči nam</a> kaj.
</p>

app/views/zombies/index.html.erb
<% provide( :title, '' ) %>

<div id="check-container" class="middle-box">
	<div>Si tudi ti med njimi?</div>
	<a href="/auth/twitter"><%= image_tag('sign-in-with-twitter.png', width: '158px',  height: '28px' ) %></a>
</div>

<%= render( 'layouts/share' ) %>

<div class="row-fluid" id="bottom">
	<div class="span5" id="bottom-left">
		<h3>Blokirani:</h3>
		<% @zombies.each do |zombie| %>
		<div class="zombie">
			<a href="https://twitter.com/<%= zombie.name %>">@<%= zombie.name %></a> <%= raw( '<em>' + zombie.message + '</em>' ) unless zombie.message.empty? %> <a href="<%= blocked_path( zombie ) %>" class="icon-arrow-right" title="Poglej zombija"></a>
		</div>
		<% end %>
	</div>
	<div class="span5" id="bottom-right">
		<a class="twitter-timeline" href="https://twitter.com/search?q=%23strankaSDS" data-widget-id="282908513997553665" width="300">Tweets about "#strankaSDS"</a>
	</div>
</div>

app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/not_blocked.html.erb
<% provide( :title, 'Nisi zombi' ) %>
<div id="not-blocked" class="middle-box">
	SDS misli da nisi zombi!
</div>

<%= render( 'layouts/share' ) %>

app/views/zombies/show.html.erb
<%
if @show_form === true
	provide( :title, 'Si zombi' )
else
	provide( :title, '@' + @zombie.name + ' je zombi' )
end
%>

<div id="blocked">
	<a href="https://twitter.com/<%= @zombie.name %>">@<%= @zombie.name %></a> 
	<%= @zombie.message unless @zombie.message.empty? || @show_form === true %>
	<% if @show_form === true %>
		<%= form_for(@zombie) do |f| %>
			<%= f.text_area( :message, placeholder: 'Povej zakaj so te blokirali ...', rows: 3 ) %>
			<div id="form-bottom">
				<%= f.submit( 'shrani', id: 'commit', class: 'btn btn-primary' ) %>
				<span id="char-counter"><%= 140 - @zombie.message.length %></span>
			</div>
		<% end %>
	<% end %>
	<%= image_tag( 'zombi.png', alt: 'SDS zombi' ) %>
</div>

<%= render( 'layouts/share', share_url: blocked_path( @zombie, only_path: false ) ) %>